export const classLevelOptions = [
    { label: 'Pre-K', value: 'pre_k' },
    { label: 'Kindergarten', value: 'kindergarten' },
    { label: '1st Grade', value: '1st_grade' },
    { label: '2nd Grade', value: '2nd_grade' },
    { label: '3rd Grade', value: '3rd_grade' },
    { label: '4th Grade', value: '4th_grade' },
    { label: '5th Grade', value: '5th_grade' },
    { label: '6th Grade', value: '6th_grade' },
    { label: '7th Grade', value: '7th_grade' },
    { label: '8th Grade', value: '8th_grade' },
    { label: '9th Grade', value: '9th_grade' },
    { label: '10th Grade', value: '10th_grade' },
    { label: '11th Grade', value: '11th_grade' },
    { label: '12th Grade', value: '12th_grade' },
    { label: 'Undergraduate Year 1', value: 'undergraduate_year_1' },
    { label: 'Undergraduate Year 2', value: 'undergraduate_year_2' },
    { label: 'Undergraduate Year 3', value: 'undergraduate_year_3' },
    { label: 'Undergraduate Year 4', value: 'undergraduate_year_4' },
    { label: 'Graduate Year 1', value: 'graduate_year_1' },
    { label: 'Graduate Year 2', value: 'graduate_year_2' },
    { label: 'PhD', value: 'phd' },
    { label: 'Adult Education', value: 'adult_education' },
];
